[package]
name = "ambers-careware/promise"
description = "Promise implementation for Roblox Luau"
version = "4.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
